### PR TITLE
Load memproof and admin data during script start-up

### LINKED ISSUE #136: Error while trying to instal core-happ
Holoport is following develop channel, currently at https://github.com/Holo-Host/holo-nixpkgs/commit/494c9089b07f6bf3084a397e6d765c7ffe276583. After registration there's a following error in the log:
```
Sep 02 08:38:20 hpos configure-holochain[105173]: Sep 02 08:38:20.515 ERROR run{config=Config { admin_port: 4444, happ_port: 42233, ui_store_folder: "/var/lib/configure-holochain/uis", happs_file_path: "/var/lib/configure-holochain/config.yaml" }}:install_and_activate_happ:register_and_install_happ: configure_holochain::websocket: error=error: InternalError("Conductor returned an error while using a ConductorApi: GenesisFailed { errors: [ConductorApiError(WorkflowError(GenesisFailure(\"Joining code invalid: incorrect registered agent key\"))), ConductorApiError(WorkflowError(GenesisFailure(\"Joining code invalid: incorrect registered agent key\")))] }")
Sep 02 08:38:20 hpos configure-holochain[105173]: Sep 02 08:38:20.515 ERROR run{config=Config { admin_port: 4444, happ_port: 42233, ui_store_folder: "/var/lib/configure-holochain/uis", happs_file_path: "/var/lib/configure-holochain/config.yaml" }}: configure_holochain: error=error: InternalError("Conductor returned an error while using a ConductorApi: GenesisFailed { errors: [ConductorApiError(WorkflowError(GenesisFailure(\"Joining code invalid: incorrect registered agent key\"))), ConductorApiError(WorkflowError(GenesisFailure(\"Joining code invalid: incorrect registered agent key\")))] }")
Sep 02 08:38:20 hpos configure-holochain[105173]: Error: error: InternalError("Conductor returned an error while using a ConductorApi: GenesisFailed { errors: [ConductorApiError(WorkflowError(GenesisFailure(\"Joining code invalid: incorrect registered agent key\"))), ConductorApiError(WorkflowError(GenesisFailure(\"Joining code invalid: incorrect registered agent key\")))] }")
Sep 02 08:38:20 hpos systemd[1]: configure-holochain.service: Main process exited, code=exited, status=1/FAILURE
Sep 02 08:38:20 hpos systemd[1]: configure-holochain.service: Failed with result 'exit-code'.
Sep 02 08:38:20 hpos systemd[1]: Failed to start configure-holochain.service.
```

For more details log into a Holoport that is experiencing this issue: `172.26.64.140`

### PR DESCRIPTION
**Pull request by peeech**
In this PR I am creating an Agent Struct which stores agent info and corresponding memproof. Agent is populated during an init process at the beginning of the script. The purpose of this PR is to isolate and move entire memproof logic into one function.
- [x] creates Agent struct
- [x] populates `self.admin`
- [x] populates `self.membrane_proof`
- [x] rewrite tests to cover multiple running scenarios

Also closes #136

### CODE REVIEW

File: src/membrane_proof.rs [hunk 1]
```diff
@@ -87,52 +83,61 @@ fn mem_proof_server_url() -> String {
...
+    let mem_proof_serialized = Arc::new(SerializedBytes::from(UnsafeBytes::from(mem_proof_bytes)));
+    Ok(mem_proof_serialized)
+}
+
+/// Creates HashMap of memproofs for dnas based on happ id
+/// which is later consumed during happ installation
+/// Currently creates memproofs only for core-app
+/// otherwise returns empty HashMap
+/// Returns HashMap<dna_name, memproof_bytes>
+pub async fn crate_vec_for_happ(
```
Comment (alastairong) [inline src/membrane_proof.rs:110]: Typo in function name?

File: src/membrane_proof.rs [hunk 2]
```diff
@@ -87,52 +83,61 @@ fn mem_proof_server_url() -> String {
...
-    let config: Config = serde_json::from_slice(&config_json)?;
-    Ok(config)
+/// Returns memproof from a file at MEM_PROOF_PATH
+/// If a file does not exist then function downloads existing mem-proof for given agent
+/// from HBS server and saves it to the file
+/// Returns error if no memproof obtained, because memproof is mandatory
+/// for core-app installation
+#[instrument(skip(admin), err)]
+pub async fn get_mem_proof(admin: Admin) -> Result<MembraneProof> {
+    if let Ok(m) = load_mem_proof_from_file() {
```
Comment (alastairong) [inline src/membrane_proof.rs:93]: As I understand the code, in the case where we:
- Have an existing valid memproof file for the environment (UID + network)
- Delete the `agent_pubkey` file to generate a new random agent

This code will load an invalid memproof file right? (i.e. invalid agent) because it doesn't ensure that the memproof is actually for that agent.

The whole point of having random agents in dev environment is so we can generate new agent_keys. Should we fix it, or should we make it a matter of process that we always delete the entire `/var/lib/configure-holochain` folder instead of only that file?

File: src/membrane_proof.rs (hunk 1 above)
Comment (peeech) [reply src/membrane_proof.rs:110]: Yeah, I should come up with better name

File: src/membrane_proof.rs (hunk 2 above)
Comment (peeech) [reply src/membrane_proof.rs:93]: Yeah good point. I was actually thinking that each time script generates [creates agent key in Lair](https://github.com/Holo-Host/hpos-configure-holochain/blob/memproof_logic_simplified/src/agent.rs#L84) it should also delete existing memproof file. That way in next step memproof will be obtained for a correct agent.

This feels much more bullet-proof than requiring devs to always delete entire `/var/lib/configure-holochain`

Comment (peeech) [reply src/membrane_proof.rs]: addressed in [982b4e7](https://github.com/Holo-Host/hpos-configure-holochain/pull/143/commits/982b4e70a41e71124209de89c93ca8fef8311e58)

File: src/membrane_proof.rs (hunk 1 above)
Comment (peeech) [reply src/membrane_proof.rs]: addressed in [982b4e7](https://github.com/Holo-Host/hpos-configure-holochain/pull/143/commits/982b4e70a41e71124209de89c93ca8fef8311e58)

**Review by zo-el — APPROVED** [review]
Nice work :tada:
